###Security UI
###Security login
POST http://localhost:3004/login/security
Content-Type: application/json

{
    "username":"Soo",
    "password":"123456"
}
###security register user account
POST http://localhost:3004/register/user 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNvbyIsImlhdCI6MTcwMzc4NTE0OSwiZXhwIjoxNzAzNzg1NzQ5fQ.3NBMo0XawL5CLTD-GDhGxpIZpFdm3iLCvlaQgqT7CYI
Content-Type: application/json

{
    "username":"uzumaki",
    "password":"123456",
    "name":"AFIFI najo",
    "email":"afifiasri@mail.com"
}
###security view all the visitor data
GET http://localhost:3004/view/visitor/security
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNvbyIsImlhdCI6MTcwMzc1MzQyNiwiZXhwIjoxNzAzNzUzNDg2fQ.Oy658AhEsUvFbOKkA2w9eWE4fomIm99KxWU3l_PZujA
###security delete the user by insert the username
DELETE http://localhost:3004/delete/user/JOHN
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNvbyIsImlhdCI6MTY4NjkyMDkwNiwiZXhwIjoxNjg2OTIwOTY2fQ.TI09kRL9KseeaRcp83PftrOSLMi27MFO-zRsy8O2Bwo
### User UI
###User login 
POST http://localhost:3004/login/user
Content-Type: application/json

{
    "username":"uzumaki",
    "password":"123456"
}
###User create visitor 
POST http://localhost:3004/create/visitor/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV6dW1ha2kiLCJpYXQiOjE3MDM3NTcwMjcsImV4cCI6MTcwMzc1NzA4N30.uQQQLrkSi9gdu9n-Hpqdzwt8Z4i9rn-autSGfq55ABU
Content-Type: application/json

{
    "visitorname": "ADLIN",
    "temperature":"27.5",
    "gender":"female",
    "ethnicity":"Islam",
    "age":"22",
    "phonenumber":"019767343"
}
###user view all visitors data that had created by that him (login user)
GET http://localhost:3004/view/visitor/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV6dW1ha2kiLCJpYXQiOjE3MDM3NTM2NzYsImV4cCI6MTcwMzc1MzczNn0.1ZlC4SBR7vAJeCnpzMziUokZl9b4RbSB9im6S6RBWEg
###user delete its visitor (by given visitorname) 
DELETE http://localhost:3004/delete/visitor/KIEW
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV6dW1ha2kiLCJpYXQiOjE3MDM3NTM5ODAsImV4cCI6MTcwMzc1NDA0MH0.J9v_1y-R0NGJ6lmFEj04vfcijYCOG_-GhQ3yIy4I6ZI
###User update their visitor info
PUT http://localhost:3004/update/visitor/topo
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InV6dW1ha2kiLCJpYXQiOjE3MDM3Njg0NjcsImV4cCI6MTcwMzc2OTA2N30.9Oz62R-kO_yBeIBkzu8qWHjhjdz88OgJi2dVAuvNd7Q

{
    "checkintime": "2002-06-23T06:30:55Z",
    "checkouttime":"2002-06-27T06:50:50Z",    
    "temperature":"26.9",
    "gender":"female",
    "ethnicity":"Kirstian",
    "age":"26",
    "phonenumber":"012345678"
}

### Visitor UI
###Visitor view their data
GET http://localhost:3004/view/visitor/KIEW
###Retrieve visitor 
POST http://localhost:3004/retrieve/visitorPass
Content-Type: application/json

{
    "visitorname": "mawajada",
    "phonenumber":"96"
}
